### ISSUE TITLE
Available on AMO?

### ISSUE THREAD

**Issue by Gitoffthelawn** [igorlogius/add-to-clipboard#1]
This was on AMO, but not seeing it there any longer.  Is it somewhere on AMO?

**Comment by igorlogius** [comment]
Mmmh, i might have forgotten about this one. 
Not sure if it is worth releasing it to AMO ... 
maybe if change it to allow the user to decide if he wants to append or prepend selections. 
I guess that would make it more useful.

**Comment by igorlogius** [comment]
Addon modified and available on AMO again. 

https://addons.mozilla.org/firefox/addon/add-to-clipboard/

Thanks for the heads up again.

**Comment by Gitoffthelawn** [comment]
You're welcome, and thanks for adding it to AMO.  And my apologies for taking so long to reply... slowly going through my GitHub Inbox!
